export { default as darkIco } from '../../icons/xs.ico'
export { default as darkIcon } from '../../icons/xs.png'
export { default as darkTray } from '../../icons/xs.png'
export { default as lightIco } from '../../icons/xs.ico'
export { default as lightIcon } from '../../icons/xs.png'
export { default as lightTray } from '../../icons/xs.png'
